---
title: "AIMS_HydroMetrics"
author: "CLB"
format: html
editor: visual
---

```{r}
#| include: false
library(data.table)
library(tidyverse, warn.conflicts = F)
options(readr.show_col_types = F)
library(googlesheets4)
library(ggthemes)
library(ggpmisc)
library(here)
library(styler)
library(streamMetabolizer)
library(rstan)
options(mc.cores = parallel::detectCores())
library(dataRetrieval)
library(scales)
library(knitr)
library(lubridate)
library(zoo)
library(nasapower)
library(imputeTS)
library(rgbif)
source(here("Code/priceDrying_15min.R"))
```

# Data

## SF Kings Creek

```{r}
#Path to QAQC pipeline
datPath <- here("Data/EXO_QAQC/01_data/04_postQaqc/KMZ/")
#List qaqc files
datPath <- list.files(datPath, "*.csv", full.names = T, recursive = T)
#Read in csvs from aims-exo-qaqc repo
kmzDat <- rbindlist(sapply(datPath, fread, simplify = F, colClasses = c("timestamp" = "character")), idcol = "exportFile")
#Clean up
kmzDat <- kmzDat %>% 
  select(-exportFile, -parameterId, -yearMonth) %>% 
  filter(betaQfSd == 0 & wetQf == 0) %>% 
  rename(dateTime = timestamp) %>% 
  select(dateTime, parameterName, value) %>% 
  mutate(dateTime = parse_date_time(dateTime, orders = c("ymd HMS", "mdy HM"), tz = "UTC")) %>% 
  pivot_wider(names_from = parameterName, values_from = value) %>% 
  select(dateTime, SW_Level_ft, SpCond_uS_cm) 
  #mutate(across(where(is.numeric), ~ replace(.x, .x < 0.01, NA))) %>% 
  #select(!(where(is.numeric) & where(~ all(is.na(.x)))))

#Lets check and fix the DF timesteps
#Date and time sequence running every 10 minutes
timeSeq <- seq(as.POSIXct(min(as_date(kmzDat$dateTime)), tz = "UTC"),
                as.POSIXct(max(as_date(kmzDat$dateTime)), tz = "UTC"),
                by = ("10 min"))
  
# simply a data frame of date and time running the course of the data set
timeSeq <- data.frame(dateTime = timeSeq)

#merge the time df
kmzDat <- merge(timeSeq, kmzDat, by = "dateTime", all = T) %>% 
  mutate(SW_Level_ft = na.approx(SW_Level_ft, maxgap = 6),
         SpCond_uS_cm = na.approx(SpCond_uS_cm, maxgap = 6),
         Site = "KMZ",
         solar.time = convert_UTC_to_solartime(dateTime, longitude = -96.587238, time.type = "mean solar"),
         isDaytime = calc_is_daytime(dateTime, 39.092353))
```

## Shane Creek

```{r}
#Path to QAQC pipeline
datPath <- here("Data/EXO_QAQC/01_data/04_postQaqc/SHN/")
#List qaqc files
datPath <- list.files(datPath, "*.csv", full.names = T, recursive = T)
#Read in csvs from aims-exo-qaqc repo
shnDat <- rbindlist(sapply(datPath, fread, simplify = F, colClasses = c("timestamp" = "character")), idcol = "exportFile")

#Long to wide and clean up
shnDat <- shnDat %>% 
  filter(alphaQf == 0 & betaQfSd == 0) %>% 
  rename(dateTime = timestamp) %>% 
  select(dateTime, parameterName, value) %>% 
  mutate(dateTime = parse_date_time(dateTime, orders = c("ymd HMS"), tz = "UTC")) %>% 
  filter(dateTime > "2023-03-24" & dateTime < "2023-07-01") %>% 
  pivot_wider(names_from = parameterName, values_from = value) %>% 
  select(dateTime, SW_Level_ft) %>% 
  mutate(SW_Level_cor = 0.99754 * SW_Level_ft + 0.21948)

#Lets check and fix the DF timesteps
#Date and time sequence running every 10 minutes
timeSeq <- seq(as.POSIXct(min(as_date(shnDat$dateTime)), tz = "UTC"),
                as.POSIXct(max(as_date(shnDat$dateTime)), tz = "UTC"),
                by = ("10 min"))
  
# simply a data frame of date and time running the course of the data set
timeSeq <- data.frame(dateTime = timeSeq)

#merge the time df
shnDat <- merge(timeSeq, shnDat, by = "dateTime", all = T)

shnDat <- shnDat %>%
  right_join(timeSeq, by = "dateTime") %>% 
    mutate(SW_Level_cor = na.approx(SW_Level_cor, maxgap = 6),
         Site = "SHN",
         solar.time = convert_UTC_to_solartime(dateTime, longitude = -96.558380, time.type = "mean solar"))
```

# Calculate Discharge

```{r}
#KMZ
kmzRC <- read_sheet("https://docs.google.com/spreadsheets/d/1DkF2Ugr6tEgnZHOGJ_UY2kW9JWH4ce8xbyzSyyA6-CI/edit#gid=0", col_types = "cDcddddddddcccc") %>% 
  filter(SiteName %in% c("SFM01") & Quality %in% c("Maybe", "Good")) %>% 
  drop_na(ManualStage_ft) %>% 
  lm(log(Q_Ls) ~ log(ManualStage_ft), .)
summary(kmzRC)
kmzRC <- coef(kmzRC)

kmzDat <- kmzDat %>% 
  mutate(Q_Ls = (kmzRC[["log(ManualStage_ft)"]] * SW_Level_ft) + kmzRC[["(Intercept)"]])

maggieDat <- kmzDat %>% 
  select(dateTime, SW_Level_ft, SpCond_uS_cm, Q_Ls) %>% 
  write_csv("~/Desktop/KingsDat_20240219.csv")

#SHN
shnRC <- read_sheet("https://docs.google.com/spreadsheets/d/1DkF2Ugr6tEgnZHOGJ_UY2kW9JWH4ce8xbyzSyyA6-CI/edit#gid=0", col_types = "cDcddddddddcccc") %>% 
  filter(SiteName %in% c("SHM01") & Quality %in% c("Maybe", "Good")) %>% 
  drop_na(ManualStage_ft) %>% 
  lm(Q_Ls ~ ManualStage_ft, .)
summary(shnRC)
shnRC <- coef(shnRC)

shnDat <- shnDat %>% 
  mutate(Q_Ls = (shnRC[["ManualStage_ft"]] * SW_Level_cor) + shnRC[["(Intercept)"]])
```

```{r}
kmzDat %>% 
  ggplot(aes(dateTime, Q_Ls))+
  geom_line() +
  labs(title = "Kings Creek Discharge",
       y = expression(Discharge~("L s"^{-1})))+
  theme_few()+
  theme(text = element_text(size = 15), axis.title.x = element_blank())+
  scale_x_datetime()

kmzDat %>% 
  ggplot(aes(dateTime, SW_Level_ft))+
  geom_line() +
  labs(title = "Kings Creek Discharge",
       y = expression(Discharge~("L s"^{-1})))+
  theme_few()+
  theme(text = element_text(size = 15), axis.title.x = element_blank())+
  scale_x_datetime()

shnDat %>% 
  ggplot(aes(dateTime, Q_Ls))+
  geom_line() +
  labs(title = "Shane Creek Discharge",
       y = expression(Discharge~("L s"^{-1})))+
  theme_few()+
  theme(text = element_text(size = 15), axis.title.x = element_blank())+
  scale_x_datetime()
```

# Calculate Hydro Metrics

## SF Kings Creek

```{r}
kmzDaily <- kmzDat %>% 
  mutate(Date = solar.time,
         site_no = "SHN",
         Flow = ifelse(Q_Ls < 0, 0, Q_Ls)) %>% 
  select(Date, site_no, Flow) %>% 
  drop_na(Flow)

kmzHydro <- metrics_fun(kmzDaily) 
kmzEvents <- eventID(kmzDaily)
kmzEvents <- kmzEvents %>% 
  full_join(kmzHydro, by = c("site_no", "event_id"))

kmzEvents %>%
  ggplot(aes(Date, q)) +
  geom_line(color = "#0000FF") +
  ylab("Q (L/s)") +
  theme_few() +
  geom_rect(data = kmzEvents %>% filter(peak_flag == 1), aes(xmin = datetime, xmax = datetime + 86400, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 0.5) +
  scale_x_datetime() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ site_no, scales = "free")
```

```{r}
shnDaily <- shnDat %>% 
  mutate(Date = solar.time,
         site_no = "SHN",
         Flow = ifelse(Q_Ls < 0, 0, Q_Ls)) %>% 
  select(Date, site_no, Flow) %>% 
  drop_na(Flow) %>%
  {
    # Find the date of the first non-zero flow
    first_nonzero_date <- .$Date[which(.$Flow > 0)[1]]

    # Truncate the date to remove time component
    first_nonzero_date <- floor_date(first_nonzero_date, "day")

    # Include data from the day before the first non-zero flow date
    start_date <- first_nonzero_date - days(1)

    # Filter the dataset to include only the rows from this start date onwards
    .[.$Date >= start_date, ]
  }
shnHydro <- metrics_fun(shnDaily) 
shnEvents <- eventID(shnDaily)
shnEvents <- shnEvents %>% 
  full_join(shnHydro, by = c("site_no", "event_id"))

shnEvents %>%
  ggplot(aes(Date, q)) +
  geom_line(color = "#0000FF") +
  ylab("Q (L/s)") +
  theme_few() +
  geom_rect(data = shnEvents %>% filter(peak_flag == 1), aes(xmin = datetime, xmax = datetime + 1440, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 1) +
  scale_x_datetime() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ site_no, scales = "free")
```

# Mountain West

```{r}
mwQ <- read_rds(here("Data/AIMS_ALL_Piezo_RatingCurve_datafile.rds")) %>% 
  select(dateTime = DateTime, Site = site, Q_Ls = Q) %>% 
  group_by(Site) %>% 
  mutate(
    dateTime = with_tz(dateTime, tzone = "UTC"),
    Q = na.approx(Q, maxgap = 10),
    siteName = case_when(
    Site == "GSS01" ~ "Gibson Jack",
    Site == "JSS01" ~ "Johnston Draw",
    Site == "DSS01" ~ "Dry Creek"
  ))



mwQ %>%
  ggplot(aes(dateTime, Q)) +
  geom_line(color = "#0000FF") +
  ylab("Q (L/s)") +
  theme_few() +
  scale_x_datetime(labels = date_format("%b '%y")) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free", ncol = 1)
```

## MW DO Data

```{r}
#Path to QAQC pipeline
qaqcPath <- here("Data/EXO_QAQC/01_data/04_postQaqc/")
#Site directories to read from
mw <- c("DRC", "GBJ", "JDR")

#Function to read data from a given site directory and add site name
readEXOdata <- function(mw) {
  sitePath <- file.path(qaqcPath, mw)
  datFiles <- list.files(sitePath, pattern = "\\.csv$", full.names = TRUE, recursive = TRUE)
  
  if (length(datFiles) > 0) {
    data <- rbindlist(lapply(datFiles, fread, colClasses = c("timestamp" = "character")), idcol = "exportFile")
    data[, siteName := mw] # Add site name column
    return(data)
  } else {
    return(NULL)
  }
}

# Read data for each site and combine
mwDO <- rbindlist(lapply(mw, readEXOdata), fill = TRUE)

mwDO <- mwDO %>% 
  filter(alphaQf == 0 & betaQfSd == 0) %>% 
  select(siteName, dateTime = timestamp, parameterName, value) %>%
  mutate(dateTime = parse_date_time(dateTime, orders = c("ymd HMS"), tz = "UTC")) %>%
  pivot_wider(names_from = parameterName, values_from = value)

mwDupes <- mwDO |>
  select(siteName, dateTime = timestamp, parameterName, value) |>
  group_by(siteName, dateTime, parameterName) |>
  summarise(values = toString(unique(value)), .groups = "drop") |>
  mutate(n = str_count(values, ",") + 1) |>
  filter(n > 1)

```
