---
title: "USGS DO and Hydro Metrics"
author: "CLB"
format: html
editor: visual
---

```{r}
#| include: false
library(data.table)
library(tidyverse, warn.conflicts = F)
options(readr.show_col_types = F)
library(googlesheets4)
library(ggthemes)
library(ggpmisc)
library(here)
library(styler)
library(streamMetabolizer)
library(rstan)
options(mc.cores = parallel::detectCores())
library(dataRetrieval)
library(scales)
library(knitr)
library(lubridate)
library(zoo)
library(nasapower)
library(imputeTS)
library(rgbif)
library(foreach)
library(doParallel)
```

# Find Data

```{r}
# Get site data from USGS
usgsSites <- readNWISsite(c("02264000","02266200","08052700","11128500")) %>%
  transmute(site_no,
            siteName = case_when(
              site_no == "02264000" ~ "Cypress Creek",
              site_no == "02266200" ~ "Whittenhorse Creek",
              site_no == "08052700" ~ "Little Elm Creek",
              site_no == "11128500" ~ "Santa Ynez River"),
            lat = dec_lat_va,
            long = dec_long_va,
            elev = alt_va * 0.3048, # ft to m
            drain_area_va = drain_area_va / 0.38610216) # sqmi to sqkm

# Get start and end dates from USGS
avalDat <- whatNWISdata(siteNumber = usgsSites$site_no, parameterCd = "00300", service = "uv") %>%
  transmute(site_no,
            startDate = begin_date,
            endDate = end_date)

usgsSites <- left_join(usgsSites, avalDat, by = "site_no")
```

# Download

```{r}
#Leaves one core free for system use
registerDoParallel(cores = detectCores() - 1)

usgsRaw <- foreach(i=1:nrow(usgsSites), .combine='rbind', .packages=c("dataRetrieval")) %dopar% {
  parameterCd <- c("00060")
  tempDat <- readNWISdv(usgsSites$site_no[i], parameterCd, usgsSites$startDate[i], usgsSites$endDate[i])
  #Rename cols to make sense
  tempDat <- renameNWISColumns(tempDat)
  return(tempDat)
}
#Stop cluster
stopImplicitCluster()


usgsDat <- usgsRaw %>% 
    transmute(Date,
              numDate = as.numeric(Date),
              site_no,
              siteName = factor(
                case_when(
                  site_no == "02264000" ~ "Cypress Creek",
                  site_no == "02266200" ~ "Whittenhorse Creek",
                  site_no == "08052700" ~ "Little Elm Creek",
                  site_no == "11128500" ~ "Santa Ynez River"),
                levels = c("Cypress Creek", "Whittenhorse Creek", "Little Elm Creek", "Santa Ynez River"),
                ordered = T),
              Q_cfs = Flow,
              Q_cms = round(Q_cfs * 0.028316847, 4), # Convert CFS to CMS and round to Ten-Thousandths to match usgs 0
              flowQuantile = rank(Q_cms) / n()) %>%  
    drop_na() %>% 
    arrange(siteName, Date)
```

## Check out data

```{r}
usgsDat %>%
  ggplot(aes(Date, Q_cms)) +
  geom_line(color = "#0000FF") +
  ylab("Q (cms)") +
  theme_few() +
  geom_rect(data = usgsDat %>% filter(Q_cms <= 0), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 0.3) +
  scale_x_date() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free")
```

# Drying Metrics

```{r}
#Flag wet and dry, find change between wet and dry period, and group each wet period into a group
usgsDat <- usgsDat %>%
  mutate(status = ifelse(Q_cms > 0, "wet", "dry")) %>%
  group_by(siteName) %>%
  mutate(change = status != lag(status, default = first(status)),
         group = cumsum(change),
         duration = 1:n()) %>%
  group_by(siteName, group) %>%
  mutate(duration = n()) %>%
  ungroup()

#Calculate days from peak discharge to drying
wetDur <- usgsDat %>%
  filter(status == "wet") %>%
  group_by(siteName, group) %>%
  mutate(peakDayIndex = which.max(Q_cms),
         lastDayIndex = max(row_number()),
         peakToDryDays = lastDayIndex - peakDayIndex) %>%
  summarize(minQ = min(Q_cms, na.rm = T),
            avgQ = mean(Q_cms, na.rm = T),
            maxQ = max(Q_cms), 
            numWetDays = n(), 
            peakToDryDays = first(peakToDryDays),
            peakQuantile = first(flowQuantile[which.max(Q_cms)])) %>% 
  filter(numWetDays > 10)

```

### Drying Rate

```{r}
# Your existing code to flag wet and dry periods and group each wet period
usgsDat <- usgsDat %>%
  mutate(status = ifelse(Q_cms > 0, "wet", "dry")) %>%
  group_by(siteName) %>%
  mutate(change = status != lag(status, default = first(status)),
         group = cumsum(change),
         duration = 1:n()) %>%
  group_by(siteName, group) %>%
  mutate(duration = n()) %>%
  ungroup()


# Calculate drying rate
wetDur <- usgsDat %>%
  filter(status == "wet") %>%
  group_by(siteName, group) %>%
  mutate(peakDayIndex = which.max(Q_cms),
         timeSincePeak = row_number() - peakDayIndex) %>%
  mutate(logQ = log(Q_cms)) %>%
  # Ensure no infinite or NaN values in logQ before proceeding
  filter(!is.infinite(logQ) & !is.nan(logQ)) %>%
  do({
    linearModel = lm(logQ ~ timeSincePeak, data = .)
    slope = coef(linearModel)[["timeSincePeak"]]
    data.frame(., recessionRate = slope)
  }) %>%
  summarize(minQ = min(Q_cms, na.rm = TRUE),
            avgQ = mean(Q_cms, na.rm = TRUE),
            maxQ = max(Q_cms),
            numWetDays = n(), 
            peakToDryDays = abs(first(timeSincePeak)),
            peakQuantile = first(flowQuantile[which.max(Q_cms)]),
            dryingRate = first(recessionRate)) %>%
  filter(numWetDays > 10)

```
