---
title: "Gibson Jack DO"
author: "CLB"
format: html
editor: visual
---

```{r}
#| include: false
library(here)
source(here("Code/paths+packages.R"))
library(preMetabolizer)
library(terra)
library(tidyterra)
library(sf)
okabeIto <- c("#0072B2", "#E69F00", "#CC79A7", "#009E73", "#56B4E9", "#D55E00", "#F0E442", "#999999", "#000000")
#KringR ECMWF API
API_User <- "connorbrown1996@gmail.com"
API_Key <- "0ef96af1-5c5d-49a8-9868-8312ee0c703b"
```

# Site Info

```{r}
#| include: false
siteInfo <- read_csv(here("Metadata/AIMS_Site_Meta.csv")) |> 
  filter(siteId %in% c("SFM01", "SHM01", "ENM01", "TLM01", "WHM01", "PRM01", "JSS01", "DSS01", "GSS01"))
gbjShed <- st_read("~/Dropbox/AIMS/GISData/GibsonJack/GibsonJack.shp")
gbjNet <- st_read("~/Dropbox/AIMS/GISData/GibsonJack/Gibson_network.shp")
```

# Field Sheets

```{r}
mwMaint <- read_sheet(
  ss = "1XFDYFzv7UuQPKCTikZTdceA4a_65YeKFP8w-R7a4G6g",
  sheet = "Maintenance",
  na = c("NA", "Na", "na", ""),
  col_types = "c"
) |>
  janitor::clean_names(case = "small_camel") |>
  drop_na(watershed) |>
  mutate(
    time = coalesce(
      arrivalTime,
      departureTime,
      startMaintenanceTime,
      endMaintenanceTime,
      samplingStartTime,
      samplingEndTime,
      timeSensorsOut,
      timeSensorsBackIn
    )
  ) |>
  mutate(
    timeClean = case_when(
      str_detect(time, "^\\d{1,2}:\\d{2}(:\\d{2})?$") ~ str_sub(time, 1, 5),
      # keep only HH:MM if HH:MM:SS
      str_detect(time, "^\\d{3}$") ~ str_c("0", str_sub(time, 1, 1), ":", str_sub(time, 2, 3)),
      # e.g. 847 → 08:47
      str_detect(time, "^\\d{4}$") ~ str_c(str_sub(time, 1, 2), ":", str_sub(time, 3, 4)),
      # e.g. 1405 → 14:05
      TRUE ~ "12:00"
    )
  ) |>
  mutate(dateTime = with_tz(parse_date_time(
    paste(date, timeClean),
    orders = c(
      "mdY HM",
      "mdY HMS",
      "%m/%d/%Y HM",
      "%m/%d/%Y HMS",
      "%m/%d/%y HM",
      "%m/%d/%y HMS"
    ),
    tz = "US/Mountain"
  ), tzone = "UTC"))


mwBgc <- read_sheet(
  ss = "1XFDYFzv7UuQPKCTikZTdceA4a_65YeKFP8w-R7a4G6g",
  sheet = "BGC",
  na = c("NA", "Na", "na", ""),
  range = "A:BF",
  col_types = "c"
  ) |>
  janitor::clean_names(case = "small_camel") |>
  drop_na(watershed) |>
  filter(site == "GSS01") |>
  mutate(time = coalesce(
    arrivalTime,
    departureTime,
    samplingStartTime,
    samplingEndTime
  )) |>
  mutate(
    timeClean = case_when(
      str_detect(time, "^\\d{1,2}:\\d{2}(:\\d{2})?$") ~ str_sub(time, 1, 5),
      # keep only HH:MM if HH:MM:SS
      str_detect(time, "^\\d{3}$") ~ str_c("0", str_sub(time, 1, 1), ":", str_sub(time, 2, 3)),
      # e.g. 847 → 08:47
      str_detect(time, "^\\d{4}$") ~ str_c(str_sub(time, 1, 2), ":", str_sub(time, 3, 4)),
      # e.g. 1405 → 14:05
      TRUE ~ "12:00"
    )
  ) |>
  mutate(dateTime = with_tz(parse_date_time(
    paste(date, timeClean),
    orders = c(
      "mdY HM",
      "mdY HMS",
      "%m/%d/%Y HM",
      "%m/%d/%Y HMS",
      "%m/%d/%y HM",
      "%m/%d/%y HMS"
    ),
    tz = "US/Mountain"
  ), tzone = "UTC")) |> 
  select(site, dateTime, ysiTemp = tempC,  Pressure_mmHg = pressureMmHg, waterPresent, notes)

gbjMaint <- mwMaint |>
  filter(watershed == "Gibson Jack") |>
  select(site, dateTime, ysiTemp, DO = do, doUnits, Pressure_mmHg = pressureMmHg, SpC_uScm = spCUScm, waterPresent, notes) |> 
  full_join(mwBgc) |> 
  select(-site, -DO, -doUnits) |> 
  mutate(dateTime = round_date(dateTime, unit = "15 minutes"))
```

# Get Stage

```{r}
mwStage <- read_csv(here("Data/MW/SUPERSENSOR.csv")) |> 
  filter(siteID == "GSS01") |> 
  select(dateTime = datetime, waterLevel_cm = finalwaterlevel, ptTemp = tempC, wetdry) |>
  mutate(
    dateTime = as.POSIXct(dateTime, format = "%m/%d/%Y %H:%M"),
    dateTime = force_tz(dateTime, tz = "America/Denver"),
  ) |> 
  drop_na(dateTime) |> 
  complete(dateTime = seq(
    floor_date(min(dateTime), "15 min"), 
    floor_date(max(dateTime), "15 min"), 
    by = "15 min"
  )) |>
  arrange(dateTime) |>
  mutate(
    across(where(is.numeric), ~ na.approx(.x, na.rm = FALSE, maxgap = 8)),
    wetdry = as.numeric(wetdry),
    waterLevel_cm = replace_na(waterLevel_cm, 0),
    waterLevel_cm = if_else(waterLevel_cm < 0, 0, waterLevel_cm)
  ) |>
  mutate(
     wetdry = case_when(
       waterLevel_cm <= 0 ~ 0,
       TRUE ~ 1
     )
   ) |> 
  filter(minute(dateTime) %% 15 == 0)


mwStage |>
    filter(!is.na(wetdry)) |>
    ggplot(aes(dateTime, waterLevel_cm, color = as.factor(wetdry))) +
    geom_point() +
    ylab("Water Level (cm)") +
    theme_few() +
    geom_rect(
      data = mwStage |> filter(is.na(wetdry)),
      inherit.aes = FALSE,
      aes(xmin = dateTime, xmax = dateTime, ymin = -Inf, ymax = Inf),
      color = "#A6A6A620"
    ) +
    scale_x_datetime() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1)
    )
   
 
```

# Get DO Data

```{r}
# Path to QAQC pipeline
qaqcPath <- here("Data/EXO_QAQC/01_data/04_postQaqc/")
# Site to load data
Sites <- c("GBJ")
# Read data for each site and combine
mwDO <- aims_read(input_dir = qaqcPath, siteId = Sites, rType = "EXOS") |> 
  filter(alphaQf == 0 & betaQfSd == 0) |>
  select(Site, dateTime = timestamp, parameterName, value) |>
  pivot_wider(names_from = parameterName,
              values_from = value,
              values_fn = mean) |>
  mutate(
    dateTime = parse_date_time(dateTime, orders = c("ymd HMS"), tz = "UTC"),
    ODO_mg_L = if_else(ODO_mg_L == 0, NA, ODO_mg_L),
    temp.water = coalesce(Temp_EXO_C, `Temp_s-can_C`, SW_Temp_PT_C, Temp_MiniDOT_C)
  ) |>
  select(Site, dateTime, DO.obs = ODO_mg_L, temp.water, SW_Level_cm)  |>
  filter(dateTime > "2022-01-01") |> 
  unique()
  #mutate(DO.obs = ifelse(DO.obs > 15, NA, DO.obs))

gbjDO <- mwDO |>
  group_by(Site) |> 
  complete(dateTime = seq(floor_date(min(dateTime), "15 min"), floor_date(max(dateTime), "15 min"), by = "15 min")) |>
  arrange(dateTime) |>
  mutate(across(where(is.numeric), ~ na.approx(.x, na.rm = F, maxgap = 10))) |>
  filter(minute(dateTime) %% 15 == 0) |> 
  ungroup() |> 
  full_join(gbjMaint, by = "dateTime") |> 
  full_join(mwStage, by = "dateTime") |> 
  mutate(
    DO.obs = if_else(wetdry == 0 & dateTime < as.POSIXct("2024-01-01"), NA_real_, DO.obs),
    DO.obs = if_else(waterLevel_cm == 0 & dateTime < as.POSIXct("2024-01-01"), NA_real_, DO.obs),
    #waterLevel_cm_pred = 1.92 + 0.461 * SW_Level_cm,
    #waterLevel_cm = coalesce(waterLevel_cm, waterLevel_cm_pred),
    waterLevel_m = waterLevel_cm * 0.01
   )

gbjDO |>
    filter(SW_Level_cm > 0 & waterLevel_cm > 0) |> 
    ggplot(aes(x = SW_Level_cm, y = waterLevel_cm)) +
  geom_point(alpha = 0.5)+
    labs(x = "Sensor Level (cm)",
         y = "Water Level (cm)") +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_poly_eq(
    aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
    formula = y ~ x,
    parse = TRUE)+
    theme_few() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1)
    )

gbjDO |>
  subset(select = c("dateTime", "Site", "DO.obs", "waterPresent", "waterLevel_m")) |>
  split(~ Site) |>
  lapply(\(df) {
    xts_data <- xts::xts(df[, c("DO.obs", "waterLevel_m")], order.by = df$dateTime)

    dy <- dygraph(xts_data, main = unique(df$Site)) |>
      dyAxis("y", label = "DO (mg/L)") |>
      dyAxis("y2", label = "Water Level (m)", independentTicks = TRUE) |>
      dySeries("DO.obs", color = "#0084a8", drawPoints = TRUE) |>
      dySeries("waterLevel_m", color = "black", axis = "y2") |>
      dyRangeSelector()
    # Add red lines for waterPresent == "N"
    red_times <- df |> filter(tolower(waterPresent) == "n") |> pull(dateTime)
    for (dt in red_times) {
      dy <- dy |> dyEvent(dt, label = "Dry", color = "red")
    }

    # Add green lines for waterPresent == "Y"
    green_times <- df |> filter(tolower(waterPresent) == "y") |> pull(dateTime)
    for (dt in green_times) {
      dy <- dy |> dyEvent(dt, label = "Wet", color = "green")
    }

    dy
  })
```

# Get Pre AIMS Gibson Jack Data

# Baro Pressure

## Gibson Jack Weather Station

```{r}
# GBJ Weather station data corrected for 520 m decrease in elevation (WX station to Super Sensor)
# so add 5.2 to Wx bp to get site bp. From Michelle S.
# https://docs.google.com/spreadsheets/d/17olxsbbn2KQQEp_z16QZycVA8jMx72gGp6_cH4W5OC0/edit?gid=0#gid=0
gbjWx <- read_csv(here("Data/MW/20201018_20231012_15min.csv")) |>
   mutate(dateTime = with_tz(force_tz(mdy_hm(datetime), tzone = "US/Mountain"), tzone = "UTC")) |>
  rename(gbjWx_kPa = baro) |>
  select(-datetime) |>
  complete(dateTime = seq(floor_date(min(dateTime, na.rm = T), "15 min"), floor_date(max(dateTime, na.rm = T), "15 min"), by = "15 min")) |>
  arrange(dateTime) |>
  mutate(gbjWx_kPa = na.approx(gbjWx_kPa, na.rm = F, maxgap = 10)) |>
  filter(minute(dateTime) %% 15 == 0) |> 
  mutate(gbjWx_adj_kPa = gbjWx_kPa + 5.2)
```

## NASA

```{r}
gbj <- siteInfo |>
  filter(siteName == "Gibson Jack") |> 
  mutate(Site = "GBJ",
         StartDate = as_date("2020-01-01"),
         EndDate = today()) |> 
  select(Site, Lat, Long, Elev_m, StartDate, EndDate)

# 
# nasaBP <- get_nasa_data(gbj)
# nasaBP <- nasaBP |> 
#   complete(dateTime = seq(floor_date(min(dateTime, na.rm = T), "15 min"), floor_date(max(dateTime, na.rm = T), "15 min"), by = "15 min")) |>
#   arrange(dateTime) |>
#   mutate(bp_mbar = na.approx(bp_mbar, na.rm = F, maxgap = 10)) |>
#   filter(minute(dateTime) %% 15 == 0) |> 
#   mutate(nasa_kPa = bp_mbar * 0.1) |> 
#   select(dateTime, nasa_kPa)
```

## NOAA

```{r}
#Find closest NOAA Station
noaaStations <- get_noaa_stations(state = "ID") |> 
  filter(END_DATE >= today()) |> 
  select(-NAME_ALIAS, -STATE_PROV, -FIPS_COUNTRY_CODE, -FIPS_COUNTRY_NAME)

closest_stations <- find_closest_station(gbj$Lat, gbj$Long, dist_km = 10)

#Load data from closest station, Pocatello Regional Airport
wbanBP <- read_csv(here("Data/MW/WBAN_24156.csv")) |>
  select(DATE, starts_with("Hourly")) |>
  mutate(DATE = with_tz(force_tz(ymd_hms(DATE), tzone = "America/Denver"), tzone = "UTC")) |> 
  drop_na(DATE) |> 
  select(
    dateTime = DATE,
    Altimeter_inHg = HourlyAltimeterSetting,
    AirTemp_F = HourlyDryBulbTemperature,
    Precipitation_in = HourlyPrecipitation,
    SeaLevelPressure_inHg = HourlySeaLevelPressure,
    StationPressure_inHg = HourlyStationPressure) |>
  mutate(WBAN_ID = "24156",
         # Convert units to metric
    Altimeter_kPa = Altimeter_inHg * 3.3863886667,
    SeaLevelPressure_kPa = SeaLevelPressure_inHg * 3.3863886667,
    StationPressure_kPa = StationPressure_inHg * 3.3863886667,
    AirTemp_C = (as.numeric(AirTemp_F) - 32) * 5/9,
    Precipitation_mm = case_when(
      Precipitation_in == "T" ~ 0.001,  # trace precipitation as 0.001 inches (~0.0254 mm)
      TRUE ~ as.numeric(Precipitation_in) * 25.4)) |> 
  left_join(closest_stations |> select(GHCND_ID, WBAN_ID, NAME_PRINCIPAL, Elev_ft = ELEV_BAROM, LAT_DEC, LON_DEC, distance_km),by = "WBAN_ID") |>
  mutate(Elev_m = as.numeric(Elev_ft) * 0.3048) |> 
  select(GHCND_ID,Elev_m, LAT_DEC, LON_DEC, dateTime, Altimeter_kPa, SeaLevelPressure_kPa, StationPressure_kPa, AirTemp_C, Precipitation_mm) |> 
  mutate(site_kPa = correct_bp(StationPressure_kPa, AirTemp_C, Elev_m, gbj$Elev_m)) |> 
  complete(dateTime = seq(floor_date(min(dateTime), "15 min"), floor_date(max(dateTime), "15 min"), by = "15 min")) |>
  fill(where(is.character), .direction = "down") |>
  arrange(dateTime) |> 
   mutate(across(where(is.numeric), ~ na.approx(.x, na.rm = F, maxgap = 5))) |> 
  filter(minute(dateTime) %% 15 == 0) |> 
  select(dateTime, noaa_kPa = site_kPa) |> 
  drop_na()
```

## Plot

```{r}

gbjBP <- gbjWx |> 
  full_join(wbanBP) |> 
 # full_join(nasaBP) |> 
  pivot_longer(
    cols = ends_with("_kPa"),
    names_to = "Source",
    values_to = "kPa"
  ) |>
  mutate(Source = str_remove(Source, "_kPa$"))

gbjBP |> 
  ggplot(aes(x = dateTime, y = kPa, color = Source, shape = Source)) +
  geom_point(alpha = 0.3, size = 1.5) +
  scale_color_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(16, 17, 15, 3)) +
  theme_minimal() +
  labs(
    title = "",
    x = "Date Time",
    y = "Pressure (kPa)",
    color = "Source",
    shape = "Source"
  ) 
```

## 

```{r}
gbjData <- mwDO |> 
  left_join(gbjBP) |> 
  mutate(DO.sat = calc_DO_sat(temp.water, kPa*10),
         DO.pctsat = (DO.obs/DO.sat)*100)


gbjData |> 
  subset(select = c("dateTime", "Site", "DO.obs")) |>
  split(~ Site) |>
  lapply(\(df) {
    xts::xts(df[, c("DO.obs")], order.by = df$dateTime) |>
      dygraph(main = unique(df$Site)) |>
      dyAxis("y", label = "DO (mg/L)") |>
      dySeries("DO.obs", color = "#0084a8", drawPoints = TRUE) |>
      dyRangeSelector()
  })


gbjData |> 
  ggplot(aes(x = dateTime, y = DO.sat, color = Source, shape = Source)) +
  geom_point(alpha = 0.3, size = 1.5) +
  scale_color_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(16, 17, 15, 3, 7, 8, 0, 4, 6)) +
  theme_few() +
  labs(
    title = "",
    x = "Date Time",
    y = "DO Saturation (mg/L)",
    color = "Source",
    shape = "Source"
  ) +
  facet_wrap(~Site, scales = "free", ncol = 1)



# Get unique Source values from the data
sources <- unique(gbjData$Source)

# Assign Dark2 palette colors
palette_colors <- brewer.pal(n = length(sources), name = "Dark2")
source_colors <- setNames(palette_colors, sources)

gbjData |>
  subset(select = c("dateTime", "Site", "Source", "DO.pctsat")) |>
  split(~ Site) |>
  lapply(\(site_df) {
    
    # Split again by Source within each Site
    source_series <- split(site_df, site_df$Source)

    # Create a list of xts series per source
    xts_list <- lapply(source_series, \(df) {
      xts::xts(df$DO.pctsat, order.by = df$dateTime)
    })

    # Combine into a single xts object
    xts_combined <- do.call(merge, xts_list)

    # Assign column names to match source names
    colnames(xts_combined) <- names(xts_list)

    # Build dygraph with one series per Source
    dy <- dygraph(xts_combined, main = unique(site_df$Site)) |>
      dyAxis("y", label = "DO (% saturation)") |>
      dyRangeSelector()

    # Add each series with matching color
    for (src in names(xts_combined)) {
      dy <- dy |> dySeries(src, color = source_colors[[src]], drawPoints = TRUE)
    }

    dy
  })
```

# Q from Evan

```{r}
mwQ <- readRDS(here("Data/MW/AIMS_ALL_Piezo_RatingCurve_datafile.rds")) |> 
  tibble() |> 
  write_csv(here("Data/MW/Discharge_EMB_20240220.csv"))

mwQsummary <- mwQ |> 
  group_by(site) |> 
  summarise(
    min_date = min(DateTime),
    max_date = max(DateTime)
  )
```
