---
title: "USGS DO Metrics"
author: "CLB"
format: html
editor: visual
---

```{r}
#| include: false
library(data.table)
library(tidyverse, warn.conflicts = F)
options(readr.show_col_types = F)
library(googlesheets4)
library(ggthemes)
library(ggpmisc)
library(here)
library(styler)
library(streamMetabolizer)
library(rstan)
options(mc.cores = parallel::detectCores())
library(dataRetrieval)
library(scales)
library(knitr)
library(lubridate)
library(zoo)
library(nasapower)
library(imputeTS)
library(rgbif)
library(foreach)
library(doParallel)
library(broom)
source(here("Code/priceDrying.R"))
```

# Find USGS Data

```{r}
# Get site data from USGS
usgsSites <- readNWISsite(c("02264000","02266200","08052700","11128500")) %>%
  transmute(site_no,
            siteName = case_when(
              site_no == "02264000" ~ "Cypress Creek",
              site_no == "02266200" ~ "Whittenhorse Creek",
              site_no == "08052700" ~ "Little Elm Creek",
              site_no == "11128500" ~ "Santa Ynez River"),
            lat = dec_lat_va,
            long = dec_long_va,
            elev = alt_va * 0.3048, # ft to m
            drainArea = drain_area_va / 0.38610216) # sqmi to sqkm

# Get start and end dates from USGS
avalDat <- whatNWISdata(siteNumber = usgsSites$site_no, parameterCd = "00300", service = "uv") %>%
  transmute(site_no,
            startDate = begin_date,
            endDate = end_date)

usgsSites <- left_join(usgsSites, avalDat, by = "site_no")
write_csv(usgsSites, here("Data/usgsSites.csv"))
```

## Download DO Data

```{r}
#Leaves one core free for system use
registerDoParallel(cores = detectCores() - 1)

usgsRawDO <- foreach(i=1:nrow(usgsSites), .combine='rbind', .packages=c("dataRetrieval")) %dopar% {
  parameterCd <- c("00300", "00010")
  tempDat <- readNWISuv(usgsSites$site_no[i], parameterCd, usgsSites$startDate[i], usgsSites$endDate[i])
  #Rename cols to make sense
  tempDat <- renameNWISColumns(tempDat)
  return(tempDat)
}
#Stop cluster
stopImplicitCluster()


usgsDO <- usgsRawDO %>% 
    transmute(dateTime,
              site_no,
              siteName = factor(
                case_when(
                  site_no == "02264000" ~ "Cypress Creek",
                  site_no == "02266200" ~ "Whittenhorse Creek",
                  site_no == "08052700" ~ "Little Elm Creek",
                  site_no == "11128500" ~ "Santa Ynez River"),
                levels = c("Cypress Creek", "Whittenhorse Creek", "Little Elm Creek", "Santa Ynez River"),
                ordered = T),
              DO.obs = DO_Inst,
              temp.water = Wtemp_Inst) %>%  
    drop_na() %>% 
  select(-site_no) %>% 
    arrange(siteName, dateTime)
```

## Download Q

```{r}
#Leaves one core free for system use
registerDoParallel(cores = detectCores() - 1)

usgsRawQ <- foreach(i=1:nrow(usgsSites), .combine='rbind', .packages=c("dataRetrieval")) %dopar% {
  parameterCd <- c("00060")
  tempDat <- readNWISdv(usgsSites$site_no[i], parameterCd, startDate = "1979-01-01", usgsSites$endDate[i])
  #Rename cols to make sense
  tempDat <- renameNWISColumns(tempDat)
  return(tempDat)
}
#Stop cluster
stopImplicitCluster()


usgsQ <- usgsRawQ %>% 
    transmute(Date,
              site_no,
              Flow,
              Flow_cms = Flow * 0.028316847) %>% 
    drop_na() %>% 
    arrange(site_no, Date)

for (i in 1:nrow(usgsSites)) {
  tempDat <- usgsQ %>% 
    filter(site_no == usgsSites$site_no[i]) %>% 
    rename(gage = site_no) %>% 
    write_csv(paste0(here("Data/USGS_Q"), usgsSites$site_no[i], ".csv"))
}
```

## Check out data

```{r}
usgsQ %>%
  ggplot(aes(Date, Flow)) +
  geom_line(color = "#0000FF") +
  ylab("Q (cfs)") +
  theme_few() +
  geom_rect(data = usgsQ %>% filter(round(Flow, 1) <= 0), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 0.3) +
  scale_x_date() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ site_no, scales = "free")
```

# Download NASA

```{r}
#Download shortwave radiation, barometric presssure, and temperature from NASAPower for each site
nasaDat <- list()
for(i in 1:nrow(usgsSites)) {
  #All sky shortwave downward radiation
  cat(paste("Downloading data for", usgsSites$siteName[i],"\n"))
  
  tempDat <- get_power(
    community = "sb",
    pars = c("PSC"),
    temporal_api = "hourly",
    lonlat = c(usgsSites$long[i], usgsSites$lat[i]),
    dates = c(usgsSites$startDate[i], usgsSites$endDate[i]),
    site_elevation = usgsSites$elev[i],
    time_standard = "UTC")
  
  cat(paste("Finished downloading data for", usgsSites$siteName[i], "\n"))
  #Fix date time stamp and convert kilopascals to millibar
  tempDat <- tempDat %>%
    mutate(Time = paste0(str_pad(HR, 2, side = "left", pad = "0"), ":00")) %>% 
    unite("dateTime", YYYYMMDD, Time, sep = " ") %>% 
    mutate(dateTime = ymd_hm(dateTime, tz = "UTC"),
           BP = PSC * 10) %>% 
    select(dateTime, BP)

  # Simply a data frame of date and time running the course of the data set
  min.fill <- data.frame(dateTime = seq(
    from = floor_date(min(tempDat$dateTime), "15 mins"), 
    to = ceiling_date(max(tempDat$dateTime), "15 mins"),
    by = "15 mins"))
  
  # Merge and interpolate gaps
  tempDat <- merge(min.fill, tempDat, by = "dateTime", all = T) %>%
    mutate(siteName = usgsSites$siteName[i],
           BP = na.approx(BP, na.rm = F, maxgap = 5))
  #Save to list
  nasaDat[[i]] <- tempDat
  #Break loop on last iteration
  if(i == nrow(usgsSites)){break}
} 

nasaDat <- do.call(rbind, nasaDat)
nasaDat <- nasaDat %>% 
  arrange(dateTime, siteName)
```

## Merge with DO

```{r}
# Merge usgsDat with nasaDat
usgsDO <- usgsDO %>% 
  left_join(nasaDat, by = c("dateTime", "siteName")) %>%
  # Get lat and long from usgsSites
  left_join(usgsSites %>% select(siteName, lat, long), by = "siteName") %>% 
  rename(utc.time = dateTime) %>%
  mutate(
    # Calc dissolved oxygen saturation and percentage saturation
    DO.sat = calc_DO_sat(
      temp.water = temp.water,
      pressure.air = BP,
      model = "garcia-benson"),
    # Calc % DO sat
    DO.pctsat = (DO.obs/DO.sat)*100, 
    # Convert UTC time to mean solar time based on longitude
    solar.time = convert_UTC_to_solartime(
      date.time = utc.time, 
      longitude = long,
      time.type = "mean solar"),
    # Determine if it is daytime
    isDaytime = calc_is_daytime(solar.time, lat = lat)) %>% 
  select(utc.time, solar.time, siteName, DO.obs, DO.sat, DO.pctsat, temp.water, BP, isDaytime) %>% 
  drop_na() %>% 
  arrange(solar.time, siteName)
```

# Calc DO Metrics

```{r}
# Daily metrics
dailyDO <- usgsDO %>% 
  mutate(Date = floor_date(solar.time, "1 day")) %>%
  group_by(siteName, Date) %>%
  summarize(
    minDO.obs = min(DO.obs, na.rm = T),
    maxDO.obs = max(DO.obs, na.rm = T),
    minDO.sat = min(DO.sat, na.rm = T),
    maxDO.sat = max(DO.sat, na.rm = T),
    minDO.pctsat = min(DO.pctsat, na.rm = T),
    maxDO.pctsat = max(DO.pctsat, na.rm = T),
    avgDO.obs = mean(DO.obs, na.rm = T),
    avgDO.sat = mean(DO.sat, na.rm = T),
    avgDO.pctsat = mean(DO.pctsat, na.rm = T),
    totalDO = n(),
    DO.hyp = sum(DO.obs <= 2, na.rm = T)
    ) %>% 
  mutate(DO.amp = maxDO.obs - minDO.obs,
         DOsat.amp = maxDO.sat - minDO.sat,
         DOpctsat.amp = maxDO.pctsat - minDO.pctsat,
         probHyp = DO.hyp / totalDO) %>% 
  arrange(siteName, Date)

#nighttime hypoxia ratio
nightHypRat <- usgsDO %>% 
  mutate(Date = floor_date(solar.time, "1 day")) %>%
  group_by(Date, siteName, isDaytime) %>% 
  summarise(DO.hyp = sum(DO.obs <= 2, na.rm = T)) %>% 
  pivot_wider(names_from = isDaytime, values_from = DO.hyp, names_prefix = "DO_hyp_") %>%
  rename(DayHyp = DO_hyp_TRUE, NightHyp = DO_hyp_FALSE) %>% 
  mutate(NHR = NightHyp / DayHyp)

#Merge DO Metrics
doMet <- dailyDO %>% 
  full_join(nightHypRat, by = c("Date", "siteName")) %>% 
  arrange(siteName, Date)

doMet %>%
  ggplot(aes(Date, probHyp)) +
  geom_point() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free")

doMet %>%
  ggplot(aes(Date, DOpctsat.amp)) +
  geom_point() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free")

doMet %>%
  ggplot(aes(Date, DO.hyp)) +
  geom_point() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free")
```

# Calc Hydro Metrics

```{r}
#Hydro metrics from Price et al.
hydroMet <- metrics_fun(usgsQ)
write_csv(hydroMet, here("Data/gagesDryingMet.csv"))  
#get event id from hydro metrics
usgsQ <- eventID(usgsQ) 
#Merge hydro metrics with ts
hydroTS <- usgsQ %>% 
  full_join(hydroMet, by = c("site_no", "event_id")) %>% 
  mutate(siteName = factor(
                case_when(
                  site_no == "02264000" ~ "Cypress Creek",
                  site_no == "02266200" ~ "Whittenhorse Creek",
                  site_no == "08052700" ~ "Little Elm Creek",
                  site_no == "11128500" ~ "Santa Ynez River"),
                levels = c("Cypress Creek", "Whittenhorse Creek", "Little Elm Creek", "Santa Ynez River"),
                ordered = T))

hydroTS %>%
  ggplot(aes(Date, q)) +
  geom_line(color = "#0000FF") +
  ylab("Q (cfs)") +
  theme_few() +
  geom_rect(data = usgsQ %>% filter(peak_flag == 1), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 0.8) +
  geom_rect(data = usgsQ %>% filter(q <= 0), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#696969",
    alpha = 0.5) +
  scale_x_date() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ site_no, scales = "free")
```

## Merge DO metrics and Q

```{r}
allMet <- hydroTS %>%
  full_join(doMet, by = c("siteName", "Date"))

allMet %>%
  ggplot(aes(drying_rate, DO.hyp)) +
  geom_point() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ siteName, scales = "free")
```

# Testing 2 weeks before drying

```{r}
testQ <- usgsQ %>% 
  mutate(siteName = factor(
                case_when(
                  site_no == "02264000" ~ "Cypress Creek",
                  site_no == "02266200" ~ "Whittenhorse Creek",
                  site_no == "08052700" ~ "Little Elm Creek",
                  site_no == "11128500" ~ "Santa Ynez River"),
                levels = c("Cypress Creek", "Whittenhorse Creek", "Little Elm Creek", "Santa Ynez River"),
                ordered = T))
  
usgsQ %>%
  ggplot(aes(Date, q)) +
  geom_line(color = "#0000FF") +
  ylab("Q (cfs)") +
  theme_few() +
  geom_rect(data = usgsQ %>% filter(peak_flag == 1), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#ff7f50",
    alpha = 0.8) +
  geom_rect(data = usgsQ %>% filter(q <= 0), aes(xmin = Date, xmax = Date + 1, ymin = -Inf, ymax = +Inf),
    fill = "#696969",
    alpha = 0.5) +
  scale_x_date() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap( ~ site_no, scales = "free")

wk2dry <- testQ %>% 
  mutate(dQ = lag(Flow) - Flow) %>% 
  filter(Flow == 0 & dQ <= 0.01 & lead(Flow) > 0) %>% 
  mutate(TwoWkPrior = Date - weeks(2)) %>% 
  rename(dryDate = date) %>% 
  select(Date, siteName, dryDate, TwoWkPrior)

wk2DO <- dailyDO %>% 
  group_by(siteName, Date) %>% 
  left_join(wk2dry, by = c("siteName", "Date")) %>% 
  filter(Date >= TwoWkPrior & Date <= dryDate)

testDO <- dailyDO %>% 
  filter(siteName == "Whittenhorse Creek" & Date >= "2011-04-07" & Date <= "2012-05-31")
Whittenhorse Creek


```
