---
title: "USGS Wetting"
author: "CLB"
format: html
editor: visual
---

```{r}
#| include: false
library(data.table)
library(tidyverse, warn.conflicts = F)
options(readr.show_col_types = F)
library(googlesheets4)
library(ggthemes)
library(ggpmisc)
library(here)
library(styler)
library(streamMetabolizer)
library(rstan)
options(mc.cores = parallel::detectCores())
library(dataRetrieval)
library(scales)
library(knitr)
library(lubridate)
library(zoo)
library(nasapower)
library(imputeTS)
library(rgbif)
library(foreach)
library(doParallel)
library(broom)
#source(here("Code/priceDrying.R"))
```

# Download USGS Q Data

```{r}
usgsSites <- read_csv(here("Data/usgsSites.csv")) %>% 
  rename(gage = site_no)
```

```{r}
#Leaves one core free for system use
registerDoParallel(cores = detectCores() - 1)

usgsRawQ <- foreach(i=1:nrow(usgsSites), .combine='rbind', .packages=c("dataRetrieval")) %dopar% {
  parameterCd <- c("00060")
  tempDat <- readNWISdv(usgsSites$gage[i], parameterCd, usgsSites$startDate[i], usgsSites$endDate[i])
  #Rename cols to make sense
  tempDat <- renameNWISColumns(tempDat)
  return(tempDat)
}
#Stop cluster
stopImplicitCluster()


usgsQ <- usgsRawQ %>%
  mutate(Date,
         gage = site_no,
         site_no = NULL,
         Flow,
         .keep = "used") %>%
  drop_na() %>%
  arrange(gage, Date)
```

## Find Rewetting Days

```{r}

wetEvents <- usgsQ %>% 
  group_by(gage) %>% 
  mutate(
    dQ = lag(Flow) - Flow,
    rewet = Flow != 0 & lag(Flow) == 0,
    dryDays = cumsum(Flow == 0) - cummax((Flow != 0) * cumsum(Flow == 0)),
    wetDays = cumsum(Flow != 0) - cummax((Flow == 0) * cumsum(Flow != 0)),
    priorDryDays = ifelse(rewet, lag(dryDays), NA_integer_),
    dryingEvent = Flow == 0 & lag(Flow) != 0,
    totalWetDays = ifelse(dryingEvent, lag(wetDays), NA_integer_),
    totalWetDays = zoo::na.locf(totalWetDays, na.rm = FALSE),
  ) %>% 
  filter(rewet) %>% 
  select(Date, gage, Flow, priorDryDays, totalWetDays) %>% 
  mutate(wetLengthDate = Date + days(totalWetDays),
         event = row_number(),
         Q_threshold = 0.25) %>% 
  rename(wet_date = Date)
```

```{r}

wetEvents <- wetEvents %>% 
  filter(totalWetDays >= 5) %>% 
  filter(!(gage == "11128500" & wet_date == "2016-04-09")) %>% 
  filter(!(gage == "11128500" & wet_date == "2017-05-07")) %>% 
  filter(!(gage == "11128500" & wet_date == "2019-12-04"))

rewetMet <- list()
for (n in 1:nrow(wetEvents)) {
  row <- wetEvents[n, ]
  cat(paste("Calculating Rewetting Metrics for", wetEvents$gage[n], "rewet date:", wetEvents$wet_date[n], "\n"))
  rewetMet[[n]] <- rewet_metrics(gageNumber = row$gage,
                                 startDate = row$wet_date,
                                 endDate = row$wetLengthDate,
                                 filePath = here("Figs/WettingEvents/"))
  #Sys.sleep(sample(1:10, 1))
}
rewetMet <- do.call(rbind, rewetMet)



#rewetMet <- rewet_metrics(gageNumber = "02264000", startDate = "2008-07-12", endDate = "2009-02-16")

```

# DO Metrics

```{r}
wetEvents <- wetEvents %>% 
  left_join(usgsSites %>% select(-startDate, -endDate, -drainArea, -siteName), by = "gage") %>% 
  filter(!(gage == "02264000" & wetLengthDate == "2025-04-27")) %>% 
  filter(!(gage == "11128500" & wet_date == "2016-10-28")) %>% 
  filter(!(gage == "11128500" & wet_date == "2017-08-24"))




doMet <- list()
for (n in 1:nrow(wetEvents)) {
  row <- wetEvents[n, ]
  cat(paste("Calculating DO Metrics for", wetEvents$gage[n], "rewet date:", wetEvents$wet_date[n], "\n"))
  doMet[[n]] <- do_metrics(site_no = row$gage,
                              start_date = row$wet_date,
                              end_date = row$wetLengthDate,
                              latitude = row$lat,
                              longitude = row$long,
                              elevation = row$elev)
  #Sys.sleep(sample(1:10, 1))
}
doMet <- do.call(rbind, doMet)


```

```{r}
gages2 <- foreign::read.dbf("/Users/connor/Downloads/gagesii_9322_sept30_2011.dbf")
```
